name: holy_beacon_sdk
description: A comprehensive Flutter SDK for scanning and detecting iBeacon and Eddystone beacons fully configurable for any developer. No longer limited to Holy devices - register any UUID you want to detect.
version: 0.1.2
homepage: https://github.com/SanJinwoong/holy-beacon-sdk
repository: https://github.com/SanJinwoong/iBeacon-Official
issue_tracker: https://github.com/SanJinwoong/iBeacon-Official/issues
documentation: https://github.com/SanJinwoong/holy-beacon-sdk/wiki

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_reactive_ble: ^5.4.0
  permission_handler: ^11.4.0
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.holybeacon.sdk
        pluginClass: HolyBeaconSdkPlugin
      ios:
        pluginClass: HolyBeaconSdkPlugin

topics:
  - beacon
  - ibeacon
  - bluetooth
  - ble
  - holy

funding:
  - https://github.com/sponsors/SanJinwoong